export enum MqttContentType {
  None = "None",
  QNA_REQUEST = "QNA_REQUEST",
  QNA_REPLY = "QNA_REPLY",
  EDI_REQUEST = "EDI_REQUEST",
  EDI_REJECT = "EDI_REJECT",
  EDI_OK = "EDI_OK",
  EDI_RECEP = "EDI_RECEP",
  EDI_FILE_ADD = "EDI_FILE_ADD",
  EDI_FILE_DELETE = "EDI_FILE_DELETE",
}
