import {BillType} from "../bill-type";
import {PharmaType} from "./pharma-type";
import {PharmaGroup} from "./pharma-group";
import {ContractType} from "../contract-type";
import {DeliveryDiv} from "../delivery-div";
import {MedicineModel} from "../medicine/medicine-model";

export class PharmaModel {
  thisPK: string = "";
  code: string = "";
  orgName: string = "";
  innerName: string = "";
  ownerName: string = "";
  taxpayerNumber: string = "";
  phoneNumber: string = "";
  faxNumber: string = "";
  zipCode: string = "";
  address: string = "";
  addressDetail: string = "";
  businessType: string = "";
  businessItem: string = "";
  billType: BillType = BillType.None;
  pharmaType: PharmaType = PharmaType.None;
  pharmaGroup: PharmaGroup = PharmaGroup.None;
  contractType: ContractType = ContractType.None;
  deliveryDiv: DeliveryDiv = DeliveryDiv.None;
  mail: string = "";
  mobilePhone: string = "";
  openDate?: Date;
  closeDate?: Date;
  retroactiveRule: string = "";
  innerSettlementRule: string = "";
  outerSettlementRule: string = "";
  etc1: string = "";
  etc2: string = "";
  imageUrl: string = "";
  inVisible: boolean = false;
  medicineList: MedicineModel[] = [];
  relationMedicineList: MedicineModel[] = [];

  init(data: PharmaModel): PharmaModel {
    this.thisPK = data.thisPK;
    this.code = data.code;
    this.orgName = data.orgName;
    this.innerName = data.innerName;
    this.ownerName = data.ownerName;
    this.taxpayerNumber = data.taxpayerNumber;
    this.phoneNumber = data.phoneNumber;
    this.faxNumber = data.faxNumber;
    this.zipCode = data.zipCode;
    this.address = data.address;
    this.addressDetail = data.addressDetail;
    this.businessType = data.businessType;
    this.businessItem = data.businessItem;
    this.billType = data.billType;
    this.pharmaType = data.pharmaType;
    this.pharmaGroup = data.pharmaGroup;
    this.contractType = data.contractType;
    this.deliveryDiv = data.deliveryDiv;
    this.mail = data.mail;
    this.mobilePhone = data.mobilePhone;
    this.openDate = data.openDate;
    this.closeDate = data.closeDate;
    this.retroactiveRule = data.retroactiveRule;
    this.innerSettlementRule = data.innerSettlementRule;
    this.outerSettlementRule = data.outerSettlementRule;
    this.etc1 = data.etc1;
    this.etc2 = data.etc2;
    this.imageUrl = data.imageUrl;
    this.inVisible = data.inVisible;
    this.medicineList = data.medicineList;
    this.relationMedicineList = data.relationMedicineList;
    return this;
  }
  copyLhsFromRhs(lhs: PharmaModel, rhs: PharmaModel): void {
    lhs.thisPK = rhs.thisPK;
    lhs.code = rhs.code;
    lhs.orgName = rhs.orgName;
    lhs.innerName = rhs.innerName;
    lhs.ownerName = rhs.ownerName;
    lhs.taxpayerNumber = rhs.taxpayerNumber;
    lhs.phoneNumber = rhs.phoneNumber;
    lhs.faxNumber = rhs.faxNumber;
    lhs.zipCode = rhs.zipCode;
    lhs.address = rhs.address;
    lhs.addressDetail = rhs.addressDetail;
    lhs.businessType = rhs.businessType;
    lhs.businessItem = rhs.businessItem;
    lhs.billType = rhs.billType;
    lhs.pharmaType = rhs.pharmaType;
    lhs.pharmaGroup = rhs.pharmaGroup;
    lhs.contractType = rhs.contractType;
    lhs.deliveryDiv = rhs.deliveryDiv;
    lhs.mail = rhs.mail;
    lhs.mobilePhone = rhs.mobilePhone;
    lhs.openDate = rhs.openDate;
    lhs.closeDate = rhs.closeDate;
    lhs.retroactiveRule = rhs.retroactiveRule;
    lhs.innerSettlementRule = rhs.innerSettlementRule;
    lhs.outerSettlementRule = rhs.outerSettlementRule;
    lhs.etc1 = rhs.etc1;
    lhs.etc2 = rhs.etc2;
    lhs.imageUrl = rhs.imageUrl;
    lhs.inVisible = rhs.inVisible;
    lhs.medicineList = rhs.medicineList;
    lhs.relationMedicineList = rhs.relationMedicineList;
  }
}
